name: Publish to GitHub Packages
on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to GitHub Packages
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@NOAA-GSL'
          # cache: 'npm'
          # cache-dependency-path: ./package-lock.json

      - name: Install npm dependencies
        run: npm ci

      # - name: Build vite library
      #   run: npm run build

      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
