name: Run Jest tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        app:
          - dev
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev

    # setting up node.js and the .npmrc file
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: npm ci --save-dev
    - run: npm test
